image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks: 
  - name: Create DB
    command: |
      gp ports await 5432
      psql -h localhost -f /scripts/create-db.sql